apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tika
  name: tika
spec:
  ports:
  - name: "8093"
    port: 8093
    targetPort: 8090
  selector:
    io.kompose.service: tika
status:
  loadBalancer: {}
