apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: activemq
  name: activemq
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alfresco/alfresco-activemq:5.15.8
    generation: null
    importPolicy: {}
    name: 5.15.8
status:
  dockerImageRepository: ""
