apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: alfresco-pdf-renderer
  name: alfresco-pdf-renderer
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alfresco/alfresco-pdf-renderer:2.1.0-EA4
    generation: null
    importPolicy: {}
    name: 2.1.0-EA4
status:
  dockerImageRepository: ""
