apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: imagemagick
  name: imagemagick
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8090
  selector:
    io.kompose.service: imagemagick
status:
  loadBalancer: {}
