apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alfresco/acs-community-ngnix:1.0.0
    generation: null
    importPolicy: {}
    name: 1.0.0
status:
  dockerImageRepository: ""
