apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: share
  name: share
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alfresco/alfresco-share:6.1.0-RC3
    generation: null
    importPolicy: {}
    name: 6.1.0-RC3
status:
  dockerImageRepository: ""
