apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: share
  name: share
spec:
  replicas: 1
  selector:
    io.kompose.service: share
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: share
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: ' -Xms500m -Xmx500m -Dalfresco.host=localhost -Dalfresco.port=8080
            -Dalfresco.context=alfresco -Dalfresco.protocol=http '
        - name: REPO_HOST
          value: alfresco
        - name: REPO_PORT
          value: "8080"
        image: ' '
        name: share
        resources:
          limits:
            memory: "1073741824"
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - share
      from:
        kind: ImageStreamTag
        name: share:6.1.0-RC3
    type: ImageChange
status: {}
