apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: solr6
  name: solr6
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alfresco/alfresco-search-services:1.3.0.1
    generation: null
    importPolicy: {}
    name: 1.3.0.1
status:
  dockerImageRepository: ""
