apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: tika
  name: tika
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alfresco/alfresco-tika:2.1.0-EA4
    generation: null
    importPolicy: {}
    name: 2.1.0-EA4
status:
  dockerImageRepository: ""
